server.port: 9000
spring.kafka.bootstrap-servers: localhost:29092
spring.kafka.producer:
  key-serializer: org.apache.kafka.common.serialization.StringSerializer
  value-serializer: org.springframework.kafka.support.serializer.JsonSerializer